### ISSUE TITLE
Update Database

### ISSUE THREAD

**Issue by bensle** [bensle/capstone-project#20]
## Value proposition

**As a** developer,
**I want to** have coordinates for each activity location
**so that** i can display the locations on a map later on

## Description
<img src=''
 width=320px>

## Acceptance criteria

- [x] each activity in the database should have to new values: longitude & latitude

## Complexity

small

## Tasks

- [x] Create branch
- [x] update all activities in Database

**Comment by ahohnsen** [comment]
Hey Ben,

As you are not implementing the map in this user story, I think the value proposition should be changed. You could also write it from the developers perspective e.g.:

As a developer,
I want to have coordinates for each activity location
so that I can display the locations on a map later on.

I think it would be also okay to integrate this in the user story, where you actually implement the map. Cause this would mean not too much additional code for a review :)

**Comment by bensle** [comment]
Updated the Vp. My last stories were all quite large and confusing in the end, so I would like to keep them a bit smaller now
